from django.db import models

# Create your models here. (id, name, bio) : id implicitly generated by django
class Author(models.Model):
    name = models.CharField(max_length=255)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name